Renew website page and structure
NTHU-SC/NTHU-SC.github.io pull request #5
Opened 2024-09-07 09:30 UTC by Catking14

**Warning! This is (probably) a massive update**

- Remove 'Members' page in side menu
- Move all posts to 'blog' 
- Renew 'Competitions' page to a timeline with a clickable card about each competition
- Add independent subpage for each competition in 'competitions' page. If a competition has a blog post, it will redirect to there
- Update the information about all competitions (except those incoming and currently updating)
- Upload team photos to `public` folder

> P.S. I don't know who should I assign for review since this one is pretty huge... So take it if anyone wants!
> P.S.-2 It's pretty interesting to organize all prizes in over a decade!

2024-09-07 11:10 UTC, Catking14 commented
Update:

- Added 2024 summer camp and winter camp post in 'Events'

2024-09-24 10:06 UTC, William-Mou requested changes
Hi @Catking14 
Please reduce the picture size to less than 1MB to prevent long loading times on the webpage.

2024-09-24 10:12 UTC, William-Mou commented
Suggestions:

The competition page could include prize for each contest. by @YiPrograms 
After clicking on a competition, some pages show name lists while others show content—this should be consistent.
Some events on the Event page are actually news and should be moved to the News page.

2025-02-15 08:31 UTC, Catking14 commented
Update
- All pages in Competitions are now in same format, with the prize and members
- Image compression to under 1MB
- Update some pages and images for latest competitions

TODO
- **Update content (blog post for latest competitions, events or news for camp...)**
- Maybe change layout for blog post link in competitions

@haotien91 @Koyingtw or someone else could help for the content?

2025-02-15 09:21 UTC, Catking14 commented
Update
- Add a news to replace news template

2025-07-02 02:19 UTC, merged

2025-07-02 10:02 UTC, William-Mou commented
Hi @Catking14 
This PR encountered a CI issue. I've updated the GitHub Actions workflow to be compatible with artifact v4, following [this migration guide](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md), and committed the changes directly to the main branch.

2025-07-02 10:13 UTC, William-Mou reviewed
Please checked issue #6 #7 ~

2025-07-02 10:16 UTC, Catking14 commented
> Please check issue #6 and #7 ~

Got it. I'll take a look and fix those problems.